// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOeoco911AQBi8tlbMgZDI_fsiRgCTDzg',
    appId: '1:124860034036:web:9fbf25a4bb47cd8cac67a1',
    messagingSenderId: '124860034036',
    projectId: 'lithe-strata-348418',
    authDomain: 'lithe-strata-348418.firebaseapp.com',
    storageBucket: 'lithe-strata-348418.appspot.com',
    measurementId: 'G-D2LH2VZ8B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0aZEVM8-Ej7NflYHFJSD-m5x4Sfreao4',
    appId: '1:124860034036:android:84201d1319f2aff0ac67a1',
    messagingSenderId: '124860034036',
    projectId: 'lithe-strata-348418',
    storageBucket: 'lithe-strata-348418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfP3mcaxu5_xEebbBa71jwmLXoDMIjtUA',
    appId: '1:124860034036:ios:78e66bdeb245c0f6ac67a1',
    messagingSenderId: '124860034036',
    projectId: 'lithe-strata-348418',
    storageBucket: 'lithe-strata-348418.appspot.com',
    iosClientId: '124860034036-b80mae4n7o206cmi2dsnq6jipmabdd1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfP3mcaxu5_xEebbBa71jwmLXoDMIjtUA',
    appId: '1:124860034036:ios:78e66bdeb245c0f6ac67a1',
    messagingSenderId: '124860034036',
    projectId: 'lithe-strata-348418',
    storageBucket: 'lithe-strata-348418.appspot.com',
    iosClientId: '124860034036-b80mae4n7o206cmi2dsnq6jipmabdd1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );
}
